version: '2'
services:
  golang:
    image: golang:latest
    working_dir: /usr/local/go/src/github.com/davidk/memberset
    environment:
      - GOPATH=/usr/local/go/src/github.com/davidk/memberset
    volumes:
      - "./:/usr/local/go/src/github.com/davidk/memberset:z"
    command: bash -c "go test -v -bench=. -benchmem -race -coverprofile=coverage.out github.com/davidk/memberset && go tool cover -html=coverage.out -o coverage.html"
